# Generated by Django 2.2.6 on 2019-11-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flores',
            name='imagen',
            field=models.ImageField(null=True, upload_to='flores'),
        ),
    ]
