"""
Django settings for floreriaUwU project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a+xqgrl^#1c629dz&881ec5*!%h9n*mcad*_wa-rbshhtyp+k8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    #'django.contrib.sites', #google
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'floreria.apps.FloreriaConfig', #incluir la aplicacion en el proyecto
    'social_django', #incluir la opcion de autentificacion con redes sociales
    'pwa', #service worker
    'fcm_django', #notificaciones push
    #login google
    #'allauth',
    #'allauth.account',
    #'allauth.socialaccount',
    #'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware', # para autentificacion de redes sociales
]

ROOT_URLCONF = 'floreriaUwU.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends', # para autentificacion de redes sociales
                'social.apps.django_app.context_processors.login_redirect', # para autentificacion de redes sociales
            ],
        },
    },
]

WSGI_APPLICATION = 'floreriaUwU.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'  #def. el nom del dir. media
MEDIA_ROOT = os.path.join(BASE_DIR,'media')# establecer ubicacio

#definicion de los modelos internos de autentificacion
AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.instagram.InstagramOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    #google
    #'allauth.account.auth_backends.AuthenticationBackend',
)
#direccion URL al momento de logearce
SOCIAL_AUTH_LOGIN_REDIRECT_URL='/'

#claves de la aplicacion facebook
SOCIAL_AUTH_FACEBOOK_KEY='2444638015751163'
SOCIAL_AUTH_FACEBOOK_SECRET='92c8288db78ea71d8a20537d0beb7cba'
#claves de la aplicacion instagram
SOCIAL_AUTH_INSTAGRAM_KEY='2444638015751163'
SOCIAL_AUTH_INSTAGRAM_SECRET='92c8288db78ea71d8a20537d0beb7cba'

#recuperar contraseña
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'felixeduardomarin100@gmail.com'
EMAIL_HOST_PASSWORD = 'fieragato2'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR,'serviceworker.js')

FCM_DJANGO_SETTINGS  = {
        " APP_VERBOSE_NAME " : "FloreriaUwU" ,
          # predeterminado: _ ('FCM Django') 
        " FCM_SERVER_KEY " : "AIzaSyDmRRka_BsH6q8DU8_maU-0lJ7AbFUNW4s" ,
          # verdadero si desea tener solo un dispositivo activo por usuario registrado a la vez 
         # predeterminado: Falso 
        " ONE_DEVICE_PER_USER " : False,
          # dispositivos a los que no se pueden enviar notificaciones, 
         #se eliminan al recibir una respuesta de error de FCM 
         # predeterminado: Falso 
        " DELETE_INACTIVE_DEVICES " : True,
}

#SITE_ID = 1 #google